#!/usr/bin/env ansible-playbook
---
  - hosts: all
    tasks:
      - name: build virtual routers
        docker_container:
          name: "{{ hostname }}"
          image: "{{ docker_image }}"
          privileged: true
        register: container
      - debug:
          var: container.ansible_facts.docker_container.NetworkSettings.IPAddress
      - debug:
          var: container.ansible_facts.docker_container.State.Health.Status
      - name: build links
        docker_container:
          name: "bridge-{{ item.left.node }}-{{ item.left.interface }}-{{ item.right.node }}-{{ item.right.interface }}"
          image: "vr-xcon"
          command: '--p2p "{{ item.left.node }}/{{ item.left.interface }}--{{ item.right.node }}/{{ item.right.interface }}"'
          links:
            - "{{ item.left.node }}"
            - "{{ item.right.node }}"
        with_items: "{{ links }}"
      - name: render configs
        template:
          src: "{{ dialect }}.j2"
          dest: "{{ render_path }}"
          backup: false
          force: true
      - name: deploy configs
        napalm_install_config:
          hostname: "{{ container.ansible_facts.docker_container.NetworkSettings.IPAddress }}"
          username: "{{ napalm_username }}"
          password: "{{ napalm_password }}"
          dev_os: "{{ napalm_driver }}"
          config_file: "{{ render_path }}"
          replace_config: true
          commit_changes: true
          get_diffs: true
          diff_file: "diff/{{ inventory_hostname }}"
