---
  - name: configure routers
    napalm_install_config:
      hostname: "{{ container.ansible_facts.docker_container.NetworkSettings.IPAddress }}"
      username: "{{ napalm_username }}"
      password: "{{ napalm_password }}"
      dev_os: "{{ napalm_driver }}"
      config_file: "{{ render_path }}"
      replace_config: true
      commit_changes: true
      get_diffs: true
      diff_file: "diff/{{ inventory_hostname }}.diff"
...
