---
  hostname: "{{ inventory_hostname }}"
  ansible_connection: local
  ansible_python_interpreter: python
  napalm_username: "vrnetlab"
  napalm_password: "VR-netlab9"
  napalm_driver: "{{ dialect }}"

  links:
    - nodes:
      - node: vr1
        interface: 1
      - node: vr2
        interface: 1
      subnets:
        ipv4: 10.1.1.0/30
        ipv6: 2001:db8:f00::/126

  render_path: "render/{{ inventory_hostname }}.conf"
  docker_image: "vr-{{ platform }}:{{ version }}"
...
